/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cch.example;

import org.apache.camel.CamelContext;
import org.apache.camel.RoutesBuilder;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.impl.DefaultCamelContext;

public class App {
    public String getGreeting() {
        return "Hello World File!";
    }

    public static void main(String[] args) throws Exception {
        CamelContext context = new DefaultCamelContext();
        context.addRoutes( 
            new RouteBuilder() {
                public void configure() throws Exception {
                    from("file:data/inbox?noop=true")
                    .to("file:data/outbox");
                };
            }
           
        );

        context.start();
        Thread.sleep(10000);
        context.stop();
    }
}
